// <auto-generated />
using System;
using MedMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedMonitor.Migrations
{
    [DbContext(typeof(MedMonitorDbContext))]
    partial class MedMonitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MedMonitor.Models.Patient", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("AdmissionDate").HasColumnType("TEXT");
                b.Property<string>("Address").HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("AllergyDescription").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<string>("BloodType").HasColumnType("TEXT");
                b.Property<DateTime>("DateOfBirth").HasColumnType("TEXT");
                b.Property<string>("Diagnoses").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<DateTime?>("DischargeDate").HasColumnType("TEXT");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Gender").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.Property<bool>("HasAllergies").HasColumnType("INTEGER");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("MiddleName").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("PhoneNumber").HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("PolicyNumber").HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasDefaultValue("Активный").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("PolicyNumber").IsUnique().HasFilter("[PolicyNumber] IS NOT NULL");
                b.ToTable("Patients");
            });

            modelBuilder.Entity("MedMonitor.Models.Relative", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Address").HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Email").HasMaxLength(150).HasColumnType("TEXT");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<bool>("IsPrimaryContact").HasColumnType("INTEGER");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("MiddleName").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<int>("PatientId").HasColumnType("INTEGER");
                b.Property<string>("PhoneNumber").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("Relationship").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("PatientId");
                b.ToTable("Relatives");
            });

            modelBuilder.Entity("MedMonitor.Models.VitalSign", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int?>("BloodPressureDiastolic").HasColumnType("INTEGER");
                b.Property<int?>("BloodPressureSystolic").HasColumnType("INTEGER");
                b.Property<int?>("HeartRate").HasColumnType("INTEGER");
                b.Property<DateTime>("MeasuredAt").HasColumnType("TEXT");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<int?>("OxygenSaturation").HasColumnType("INTEGER");
                b.Property<int>("PatientId").HasColumnType("INTEGER");
                b.Property<string>("RecordedBy").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<int?>("RespiratoryRate").HasColumnType("INTEGER");
                b.Property<decimal?>("Temperature").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("PatientId");
                b.ToTable("VitalSigns");
            });

            modelBuilder.Entity("MedMonitor.Models.Relative", b =>
            {
                b.HasOne("MedMonitor.Models.Patient", "Patient")
                    .WithMany("Relatives")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Patient");
            });

            modelBuilder.Entity("MedMonitor.Models.VitalSign", b =>
            {
                b.HasOne("MedMonitor.Models.Patient", "Patient")
                    .WithMany("VitalSigns")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Patient");
            });

            modelBuilder.Entity("MedMonitor.Models.Patient", b =>
            {
                b.Navigation("Relatives");
                b.Navigation("VitalSigns");
            });
#pragma warning restore 612, 618
        }
    }
}
